-- MySQL Script generated by MySQL Workbench
-- Ter 01 Ago 2017 16:44:03 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ordersmgt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ordersmgt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ordersmgt` DEFAULT CHARACTER SET utf8 ;
USE `ordersmgt` ;

-- -----------------------------------------------------
-- Table `ordersmgt`.`tab_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordersmgt`.`tab_customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `credit` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordersmgt`.`tab_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordersmgt`.`tab_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `unit_price` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordersmgt`.`tab_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordersmgt`.`tab_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_customer` INT NOT NULL,
  `order_date` DATETIME NOT NULL,
  `required_date` DATETIME NULL,
  `shipped_date` DATETIME NULL,
  `paid` DECIMAL(15,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tab_orders_tab_customers1_idx` (`id_customer` ASC),
  CONSTRAINT `fk_tab_orders_customers`
    FOREIGN KEY (`id_customer`)
    REFERENCES `ordersmgt`.`tab_customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordersmgt`.`tab_order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordersmgt`.`tab_order_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_product` INT NOT NULL,
  `id_orders` INT NOT NULL,
  `discount` DECIMAL(15,2) NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tab_orders_tab_products_idx` (`id_product` ASC),
  INDEX `fk_tab_order_details_tab_orders1_idx` (`id_orders` ASC),
  CONSTRAINT `fk_tab_orders_products`
    FOREIGN KEY (`id_product`)
    REFERENCES `ordersmgt`.`tab_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_order_details_orders`
    FOREIGN KEY (`id_orders`)
    REFERENCES `ordersmgt`.`tab_orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordersmgt`.`tab_product_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordersmgt`.`tab_product_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_products` INT NOT NULL,
  `cost` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`id`, `id_products`),
  INDEX `fk_tab_product_detail_tab_products1_idx` (`id_products` ASC),
  CONSTRAINT `fk_tab_product_detail_tab_products1`
    FOREIGN KEY (`id_products`)
    REFERENCES `ordersmgt`.`tab_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
